### ISSUE TITLE
Copia File

### ISSUE THREAD

**Issue by FabioZTessitore** [Raffaelefrn/caratteri#1]
Cerca di capire cosa fa il programma copia_file.c e soprattutto come lo fa. Fammi sapere

**Comment by Raffaelefrn** [comment]
Il file copia_file.c ci permette semplicemente di copiare un carattere,
quando questo viene digitato da tastiera il ciclo si ripere per due volte
stampandolo e "copiandolo" a sua volta per due volte. L'operatore getchar
ci permette semplicemente di immettere un carattere all'interno della
variabile C, putchar invece di stampare a video tutto ciò che noi scriviamo
e che viene messo nella variabile C. Per quanto riguarda il ciclo questo si
ripeterà all'infinito fino a quando non si premeranno i tasti CTRL+D,
eguagliando la variabile C al EOF il quale dovrebbe essere se non sbaglio
-1.

2015-12-22 22:42 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
Prendi ad esempio una instruzione del tipo:

``` C
int a, b, c;
a = b = c = 10;
```

Dovresti sapere che serve ad assegnare il valore 10 alle variabili intere `a, b, c`.
Nel dettaglio quello che succede è che viene effettuata prima l'operazione

``` C
c = 10
```

Nel linguaggio C una **assegnazione vale il valore assegnato**, in altre parole tutta l'istruzione `c = 10` **vale** il valore assegnato 10.
Questo permette di proseguire nella catena:

``` C
a = b = (c = 10)   --->  a = b = 10  ---> a = (b = 10)  ---> a = 10
```

**Comment by FabioZTessitore** [comment]
Nel nostro caso, come condizione del ciclo while c'è:

``` C
(c=getchar())!=EOF
```

Quindi prima viene eseguita la funzione `getchar()` (legge un carattere dal buffer di input), poi il carattere letto viene assegnato a `c`.
Infine tutta l'istruzione `(c=getchar())` **vale** il carattere letto che può essere confrontato con EOF per stabilire se nel file di input ci sono ancora caratteri da leggere.

**Comment by Raffaelefrn** [comment]
più ho meno ho capito

Il giorno 23 dicembre 2015 23:31, Fabio Z Tessitore <
notifications@github.com> ha scritto:
