### ISSUE TITLE
Conta caratteri

### ISSUE THREAD

**Issue by FabioZTessitore** [Raffaelefrn/caratteri#2]
Prendendo spunto da copia_file.c crea un programma conta_caratteri.c che conta i caratteri presenti in un file
Crea anche un file testo.txt con pochi caratteri da usare per fare le prove.

Per l'esecuzione:

``` bash
$ ./conta_caratteri < testo.txt
```

**Comment by Raffaelefrn** [comment]
programma completato, compilato, eseguito e caricato, spero vada bene

2015-12-24 13:10 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
gli spazi non sono caratteri?

ps. un po' di attenzione a come scrivi il codice. le indentazioni sono importanti

**Comment by Raffaelefrn** [comment]
va bene ora modifico e ricarico

Il giorno 24 dicembre 2015 13:56, Fabio Z Tessitore <
notifications@github.com> ha scritto:
