### ISSUE TITLE
Spazi multipli

### ISSUE THREAD

**Issue by FabioZTessitore** [Raffaelefrn/caratteri#4]
creare un programma che elimina spazi multipli da un file

**Comment by Raffaelefrn** [comment]
programma finito, compilato ed eseguito, caricato con il dovuto file di
prova

2015-12-24 18:01 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
ho aggiunto spazi al file di prova e non funziona, devi riguardarlo

**Comment by Raffaelefrn** [comment]
ma come ? io ho fatto varie prove e a me funziona bene, lei che prova ha
fatto ? così lo confronto

2015-12-24 19:04 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
ti ho inviato le modifiche al file di test. Fai il pull

**Comment by Raffaelefrn** [comment]
programma aggiornato e migliorato

Il giorno 24 dicembre 2015 19:06, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by Raffaelefrn** [comment]
prof ora devo compiere l'impresa più ardua, mangiare tutto il cenone della
vigilia, buona Natale, buona vigilia e sopratutto buon cenone a lei e
family :)

Il giorno 24 dicembre 2015 20:01, Raffaele jo raffa.fari57@gmail.com ha
scritto:

**Comment by FabioZTessitore** [comment]
thanks!
e altrettanto a tutti

**Comment by Raffaelefrn** [comment]
la ringrazio, il programma va bene ?

2015-12-24 22:41 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
certo che no

**Comment by Raffaelefrn** [comment]
che altro ci manca

2015-12-27 19:41 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
come prima cosa ho riformattato il testo. Non si capiva niente. Se vuoi collaborare con altre persone devi imparare ad usare degli stili coerenti

**Comment by FabioZTessitore** [comment]
riguardo all'algoritmo ... la logica non è delle più chiare.
In più nel tuo output se è vero che non ci sono spazi multipli è anche vero che vengono sostituiti da degli zero. Stampare un carattere di codice zero non ha senso

![dump_output_1](https://cloud.githubusercontent.com/assets/3002194/12011594/3db8150e-acd5-11e5-9b51-2d0d9750a83b.png)

![dump_output_2](https://cloud.githubusercontent.com/assets/3002194/12011599/7d43e874-acd5-11e5-88bb-5a41c09f0a99.png)

**Comment by FabioZTessitore** [comment]
il tuo programma non dovrebbe stampare 0 al posto degli spazi multipli. Deve decidere se stampare o meno il carattere

**Comment by Raffaelefrn** [comment]
Ho capito come procedere, solo che non ho un poco di tempo libero per
scrivere il programma
Il 29/dic/2015 16:11 "Fabio Z Tessitore" notifications@github.com ha
scritto:

**Comment by Raffaelefrn** [comment]
programma finito, compilato ed eseguito ed in fine caricato, penso sia
corretto ora e mi scuso per l'attesa

Il giorno 30 dicembre 2015 11:37, Raffaele jo raffa.fari57@gmail.com ha
scritto:

**Comment by FabioZTessitore** [comment]
In verità non hai caricato niente

**Comment by Raffaelefrn** [comment]
ma come ? ci riprovo

2016-01-05 13:43 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by Raffaelefrn** [comment]
ci sta, elimina spazi multipli aggiornato

Il giorno 5 gennaio 2016 13:53, Raffaele jo raffa.fari57@gmail.com ha
scritto:

**Comment by FabioZTessitore** [comment]
``` c
if ( ( (c==' ') || (c!=' ') )   &&   (conta<2) )
```

chiedere se c è uguale oppure è diverso da spazio non ha molto senso (è sempre vero). L'unica cosa che conta in questo if è l'ultima parte (conta<2).

``` c
if ( (c!=' ') && (c!=0) )
```

qui non si capisce perché controlli che c sia diverso da zero. Forse è un refuso della vecchia versione

Detto questo, il programma è assolutamente contorto e incomprensibile (probabilmente anche a te tra qualche giorno). Ma questo era lo scopo, farti spremere il cervello.
Adesso però facciamo come dico io, cioè con un diagramma degli stati. Lascia perdere il codice per un attimo e cerca di compilare questa tabella.

### Stato Carattere

| Input | Output | Prossimo Stato |
| --- | --- | --- |
| ? | ? | ? |

A quali input dobbiamo prestare attenzione?

**Comment by Raffaelefrn** [comment]
Prof scusatemi ma non ho capito, mica potrebbe rispiegarmi meglio il fatto
della tabella, grazie

Il giorno 5 gennaio 2016 15:46, Fabio Z Tessitore notifications@github.com
ha scritto:

**Comment by FabioZTessitore** [comment]
In quella tabella ci sono 3 colonne. L'input, L'output e il prossimo stato.
Sei tu a decidere per un certo input che output vuoi e quale sara' il prossimo stato.
Esempio.
Mettiamo che incontriamo un carattere (non spazio). Cosa dovresti fare? Stamparlo.
Allora avremo che l'input è `c!=' '`, l'output sarà proprio `c`. Il prossimo stato dipende da quello che deve fare il programma. Nel nostro caso l'aver incontrato un carattere non spazio lascia immutato lo stato del sistema e quindi lo stato sarà ancora `Carattere`

### Stato Carattere

| Input | Output | Prossimo Stato |
| --- | --- | --- |
| `c!=' '` | `c` | `Carattere` |
| `c==' '` | ? | ? |

Che dovrebbe succedere quando incontri uno spazio?

**Comment by FabioZTessitore** [comment]
Devi ancora finire questo programma
