### ISSUE TITLE
Elimina Commenti

### ISSUE THREAD

**Issue by FabioZTessitore** [Raffaelefrn/caratteri#5]
Devi fare anche elimina commenti

**Comment by Raffaelefrn** [comment]
ho caricato elimina commenti

2016-01-13 18:38 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by Raffaelefrn** [comment]
prof ho apportato le modifiche che mi avevate detto, attendo sue notizie.

Il giorno 18 gennaio 2016 20:10, Raffaele jo raffa.fari57@gmail.com ha
scritto:

**Comment by FabioZTessitore** [comment]
gli ultimi due if dovevano essere così o hai dimenicato gli else?

**Comment by Raffaelefrn** [comment]
modifiche apportate, prof appena mi risponde avrei una cosa da chiederle
riguardo Arduino e altri micro controllori per quanto riguarda un mio
progetto personale, e se possibile vorrei un suoi aiuto.Grazie e buona
domenica

2016-01-21 20:28 GMT+01:00 Fabio Z Tessitore notifications@github.com:
